Eshop/urls.py
from django.contrib import admin
from django.urls import path, include
from Eshop import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('store.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('base.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = "DJANGO_MEDIC_SHOP".title()

base/urls.py
from django.urls import path
from .views import (change_password, logout_user, register_user,
                    login_user, profile, delete_account)

urlpatterns = [
    path('register', register_user, name='register'),
    path('login', login_user, name='login'),
    path('logout', logout_user, name="logout"),
    path('profile', profile, name="profile"),
    path("delete-account", delete_account, name="delete-account"),
    path("change-password", change_password, name="change-password")
]

cart/models.py
from store.models import Item
from base.models import Customer
from django.utils import timezone
from django.db import models

from .choices import PaymentChoice
from.validators import item_count_ge_zero, coupon_validation


# class Checkout(models.Model):
#     user = models.ForeignKey(Customer, on_delete=models.CASCADE)
#     address = models.TextField(blank=False, null=False)
#     address2 = models.TextField(blank=True)
#     zip_code = models.PositiveIntegerField()
#     country = models.CharField(max_length=70, choices=CountryChoices.choices)


class Coupon(models.Model):
    code = models.CharField(max_length=50, unique=True)
    user = models.ManyToManyField(
        Customer, related_name="promo_code", blank=True)
    short_description = models.CharField(max_length=100)
    valid_till = models.DateField(
        default=timezone.now, validators=[coupon_validation])
    discount_amount = models.PositiveIntegerField(default=0)

    def __str__(self) -> str:
        return f"{self.code}"

    @property
    def valid(self):
        return self.valid_till > timezone.now().date()


class Order(models.Model):
    ordered_at = models.DateTimeField(auto_now_add=True)
    payment_options = models.CharField(
        max_length=50, choices=PaymentChoice.choices)
    is_delivered = models.BooleanField(default=False)
    user = models.ForeignKey(Customer, on_delete=models.CASCADE)
    items = models.ManyToManyField(Item, blank=False)


class OrderedItem(models.Model):
    user = models.ForeignKey(Customer, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    item_count = models.IntegerField(
        default=1, validators=[item_count_ge_zero])

    def __str__(self) -> str:
        return f"{self.user}:{self.item}"

    @property
    def total_price(self):
        return self.item_count*self.item.product.price

    @property
    def product(self):
        return self.item.product

    @property
    def item_price(self):
        return self.item.product.price


class Cart(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(Customer, on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderedItem, blank=True)
    coupons = models.ManyToManyField(Coupon, blank=True)

    class Meta:
        ordering = '-updated_at',

    def __str__(self) -> str:
        return f"{self.user}"

    @property
    def total_price(self):
        return sum([item.total_price for item in self.items.all()])

    @property
    def discount(self):
        return sum([coupon.discount_amount for coupon in self.coupons.all()])

    @property
    def final_price(self):
        return self.total_price - self.discount

templates/components/badges.html
<div class="row px-xl-5 py-3">
    <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
        <div class="d-flex align-items-center border mb-4" style="padding: 30px;">
            <h1 class="fa fa-check text-primary m-0 mr-3"></h1>
            <h5 class="font-weight-semi-bold m-0">Quality Product</h5>
        </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
        <div class="d-flex align-items-center border mb-4" style="padding: 30px;">
            <h1 class="fa fa-shipping-fast text-primary m-0 mr-2"></h1>
            <h5 class="font-weight-semi-bold m-0">Free Shipping</h5>
        </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
        <div class="d-flex align-items-center border mb-4" style="padding: 30px;">
            <h1 class="fas fa-exchange-alt text-primary m-0 mr-3"></h1>
            <h5 class="font-weight-semi-bold m-0">14-Day Return</h5>
        </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
        <div class="d-flex align-items-center border mb-4" style="padding: 30px;">
            <h1 class="fa fa-phone-volume text-primary m-0 mr-3"></h1>
            <h5 class="font-weight-semi-bold m-0">24/7 Support</h5>
        </div>
    </div>
</div>

templates/components/carousels.html
{%load static%}
<div
  div
  id="carouselExampleIndicators"
  class="carousel slide"
  data-mdb-ride="carousel"
>
  <div class="carousel-inner">
    <div class="carousel-indicators">
      <button
        type="button"
        data-mdb-target="#carouselBasicExample"
        data-mdb-slide-to="0"
        class="active"
        aria-current="true"
        aria-label="Slide 1"
      ></button>
      <button
        type="button"
        data-mdb-target="#carouselBasicExample"
        data-mdb-slide-to="1"
        aria-label="Slide 2"
      ></button>
      <button
        type="button"
        data-mdb-target="#carouselBasicExample"
        data-mdb-slide-to="2"
        aria-label="Slide 3"
      ></button>
      <button
        type="button"
        data-mdb-target="#carouselBasicExample"
        data-mdb-slide-to="3"
        aria-current="true"
        aria-label="Slide 4"
      ></button>
    </div>

    <div class="carousel-item active" style="height: 500px">
      <img
        class="img-fluid"
        src="{% static 'images/carosel-image-2.jpg'%}"
        alt="Image"
      />
      <div
        class="carousel-caption d-flex flex-column align-items-center justify-content-center"
      >
        <div class="p-3" style="max-width: 700px">
          <h4 class="text-light text-uppercase font-weight-medium mb-3">
            10% Off Your First Order
          </h4>
          <h3 class="text-white font-weight-semi-bold mb-4">
            Find All You Need In One Place
          </h3>
        </div>
      </div>
    </div>
    <div class="carousel-item" style="height: 500px">
      <img
        class="img-fluid"
        src="{% static 'images/carosel-image-1.jpg'%}"
        alt="Image2"
      />
      <div
        class="carousel-caption d-flex flex-column align-items-center justify-content-center"
      >
        <div class="p-3" style="max-width: 700px">
          <h4 class="text-light text-uppercase font-weight-medium mb-3">
            Reasonable Prices
          </h4>
          <h3 class="text-white font-weight-semi-bold mb-4">
            The Prices are regular to that of market
          </h3>
        </div>
      </div>
    </div>
    <div class="carousel-item" style="height: 500px">
      <img
        class="img-fluid"
        src="{% static 'images/carosel-image-3.jpg'%}"
        alt="Image2"
      />
      <div
        class="carousel-caption d-flex flex-column align-items-center justify-content-center"
      >
        <div class="p-3" style="max-width: 700px">
          <h4 class="text-light text-uppercase font-weight-medium mb-3">
            We Love your Users
          </h4>
          <h3 class="text-white font-weight-semi-bold mb-4">
            Users are first priority for us
          </h3>
        </div>
      </div>
    </div>
    <div class="carousel-item" style="height: 500px">
      <img
        class="img-fluid"
        src="{% static 'images/carosel-image-4.jpg'%}"
        alt="Image2"
      />
      <div
        class="carousel-caption d-flex flex-column align-items-center justify-content-center"
      >
        <div class="p-3" style="max-width: 700px">
          <h4 class="text-light text-uppercase font-weight-medium mb-3">
            A different Way
          </h4>
          <h3 class="text-white font-weight-semi-bold mb-4">
            Get to know the different way of shopping
          </h3>
        </div>
      </div>
    </div>
  </div>
</div>

templates/components/footer.html
<footer class="section-footer bg-light mt-3">
  <div class="container">
    <section class="footer-main py-4">
      <div class="row">
        <aside class="col-lg-4">
          <article class="me-lg-4 mb-4">
            <img
              src="https://cdn-icons-png.flaticon.com/512/5224/5224110.png"
              height="45"
              class="logo-footer" />
            <p class="mt-3">
              Hopefully you liked our webiste, we will connect with you. Please
              follow our social-contracts
            </p>
            <nav>
              <a
                class="btn btn-icon btn-light"
                title="Facebook"
                target="_blank"
                href="#"
                ><i class="fab fa-facebook-f"></i
              ></a>
              <a
                class="btn btn-icon btn-light"
                title="Instagram"
                target="_blank"
                href="#"
                ><i class="fab fa-instagram"></i
              ></a>
              <a
                class="btn btn-icon btn-light"
                title="Youtube"
                target="_blank"
                href="#"
                ><i class="fab fa-youtube"></i
              ></a>
              <a
                class="btn btn-icon btn-light"
                title="Twitter"
                target="_blank"
                href="#"
                ><i class="fab fa-twitter"></i
              ></a>
            </nav>
          </article>
        </aside>
      </div>
    </section>
    <section
      class="footer-bottom d-flex justify-content-lg-between border-top pb-2">
      <p class="text-muted mb-0">© 2021 Templatemount. All rights reserved.</p>
      <nav>
        <a href="#" class="px-2">Support</a>
        <a href="#" class="px-2">Privacy &amp; Cookies</a>
        <a href="#" class="px-2">Accessibility</a>
      </nav>
    </section>
  </div>
</footer>

templates/components/messages.html
{% if messages%}
  {% for message in messages %} 
    {% if message.tags == 'success'%}
      <div
        class="alert alert-dismissible fade show alert-success"
        role="alert"
        data-mdb-color="success"
        id="customxD">
        <strong>{{message}}</strong>

        <button
          type="button"
          class="btn-close"
          data-mdb-dismiss="alert"
          aria-label="Close"></button>
      </div>
    {%else%}
      <div
        class="alert alert-dismissible fade show alert-{{message.tags}}"
        role="alert"
        data-mdb-color="{{message.tags}}"
        id="customxD">
        <strong>{{message}}</strong>
        <button
          type="button"
          class="btn-close"
          data-mdb-dismiss="alert"
          aria-label="Close"></button>
      </div>
    {%endif%}
  {% endfor %}
{%endif%}

templates/components/navbar.html
{% load search_tags %}
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-2">
  <div class="container">
    <a class="navbar-brand me-2" href="{%url 'home'%}">
      <img
        src="https://cdn-icons-png.flaticon.com/512/5224/5224110.png"
        height="16" />
    </a>
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarButtonsExample"
      aria-controls="navbarButtonsExample"
      aria-expanded="false"
      aria-label="Toggle navigation">
      <i class="fas fa-bars"></i>
    </button>

    <div class="collapse navbar-collapse" id="navbarButtonsExample">
      <div class="d-flex me-auto">
        <ul class="navbar-nav mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="{%url 'categories'%}">Categories</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{%url 'products'%}">Products</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{%url 'orders'%}">Orders</a>
          </li>
        </ul>
      </div>
      {%search_form%}
      <ul class="navbar-nav">
        <li class="nav-item me-3 me-lg-1">
          <a class="nav-link" href="{%url 'cart'%}">
            <i class="fa-solid fa-shopping-bag"></i>
            <span class="badge rounded-pill badge-notification bg-danger">
              {{user.customer.cart_set.get.items.count}}</span
            >
          </a>
        </li>
        <li class="nav-item me-3 me-lg-1">
          <a class="nav-link" href="{% url 'favourites'%}">
            <i class="fa-solid fa-heart"></i>
            <span class="badge rounded-pill badge-notification bg-danger"
              >{{user.customer.item_favorite.count}}</span
            >
          </a>
        </li>
        <li class="nav-item me-3 me-lg-1">
          <a class="nav-link" href="{% url 'wishlist'%}">
            <i class="fa-solid fa-star"></i>
            <span class="badge rounded-pill badge-notification bg-danger"
              >{{user.customer.item_wishlist.count}}</span
            >
          </a>
        </li>
        <li class="nav-item dropdown">
          <a
            class="nav-link d-sm-flex align-items-sm-center"
            href="#"
            id="dropdownMenuButton"
            data-mdb-toggle="dropdown"
            aria-expanded="false">
            <img
              src="{{user.customer.image.url}}"
              class="rounded-circle"
              style="height: 32px; width: 32px"
              alt="Navbar profile image" />
            <strong class="d-none d-sm-block ms-1">
              {%if user.customer.first_name %} {{user.customer.first_name}}
              {%else%} {{user.customer}} {%endif%}
            </strong>
          </a>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <li>
              <a class="dropdown-item" href="{% url 'profile'%}">My profile</a>
            </li>
            <li>
              <a class="dropdown-item" href="{%url 'logout'%}">Logout</a>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/components/navbar_search.html
<form
  action="{%url 'search_product'%}"
  class="d-flex input-group w-auto"
  novalidate>
  {{form}}
  <button
    class="btn btn-outline-primary"
    type="submit"
    data-mdb-ripple-color="dark">
    Search
  </button>
</form>